base_api:
  port: "8080" # // rag-pipeline api port
  collection_name: "api_collection"
  
chunk:
  size: 300
  overlap: 55

retrieval:
  top_k: 4

qdrant:
  host: "qdrant"
  port: 6334

embedding:
  model_dimension: 768
  model_name: "nomic-embed-text"
  endpoint: "/api/embed"

ollama:
  base_url: "http://ollama:11434"

generator:
  model_name: "tinyllama" # "tinyllama" "llama3.2:3b" "phi3:mini"
  endpoint: "/api/generate"

evaluation:
  retrieval_data_path: "eval_data/retrieval/notre_dame_qa_chunks.json"
  generation_data_path: "eval_data/generation/notre_dame_qa_min.json"
  source_data_path: "eval_data/notre_dame_contexts.txt"
  collection_name: "eval_collection"
